#!/usr/bin/bash

# Please run this script from within the Distrobox if
# you do not have Ubuntu + ROS 2 installed on your machine.

# Build the overlay.
script_dir="$(cd "$(dirname "$0")" && pwd)"
overlay_dir="$(cd "$script_dir/../overlay_ws" && pwd)"

# Remember the previous directory.
prev_dir=$(pwd)

# Enter the workspace.
cd $overlay_dir

# Build the workspace.
MAKEFLAGS="-j 6" colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-O3" --allow-overriding compressed_depth_image_transport realsense2_camera realsense2_camera_msgs realsense2_description rtabmap_odom rosapi rosapi_msgs rosbridge_library rosbridge_msgs rosbridge_server rosbridge_suite rosbridge_test_msgs moveit_msgs

# Copy OpenVDB libs to install directory.
cp ./build/spatio_temporal_voxel_layer/openvdb/lib/libopenvdb.so ./install/spatio_temporal_voxel_layer/lib/
cp ./build/spatio_temporal_voxel_layer/openvdb/lib/libopenvdb.so.10.0 ./install/spatio_temporal_voxel_layer/lib/
cp ./build/spatio_temporal_voxel_layer/openvdb/lib/libopenvdb.so.10.0.1 ./install/spatio_temporal_voxel_layer/lib/

# Return to the previous directory.
cd $prev_dir
